// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "effect",
  id: "skymen_masked_drop_shadow",
  name: "Masked Drop Shadow",
  version: "1.0.0.0",
  category: "blend",
  // "distortion",
  // "normal-mapping",
  // "tiling",
  // "other",
  // "color",
  author: "skymen",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "Applies a drop shadow to the background using a mask",
  supportedRenderers: ["webgl" /* "webgl2", "webgpu" */],
  blendsBackground: true,
  usesDepth: false,
  crossSampling: false,
  preservesOpaqueness: false,
  animated: false,
  mustPredraw: false,
  extendBox: {
    horizontal: 0,
    vertical: 0,
  },
  isDeprecated: false,
  parameters: [
    /*
    {
      type:
        "float"
        "percent"
        "color"
      ,
      id: "property_id",
      value: 0,
      uniform: "uPropertyId",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Property Name",
      desc: "Property Description",
    }
    */
    {
      type: "float",
      id: "shadow_distance",
      value: 10,
      uniform: "uShadowDistance",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Shadow Distance",
      desc: "The distance of the shadow from the object",
    },
    {
      type: "float",
      id: "extra_displace_distance",
      value: 0,
      uniform: "uDisplaceExtra",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Extra Displace Distance",
      desc: "The extra distance to displace the mask",
    },
    {
      type: "float",
      id: "shadow_angle",
      value: 90,
      uniform: "uShadowAngle",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Shadow Angle",
      desc: "The angle of the shadow",
    },
    {
      type: "percent",
      id: "shadow_opacity",
      value: 1,
      uniform: "uShadowOpacity",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Shadow Opacity",
      desc: "The opacity of the shadow",
    },
    {
      type: "color",
      id: "shadow_color",
      value: [0, 0, 0],
      uniform: "uShadowColor",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Shadow Color",
      desc: "The color of the shadow",
    },
  ],
};
